apiVersion: v1
kind: Service
metadata:
  name: datanode
  labels:
    app: datanode
  namespace: hadoop
spec:
  clusterIP: None
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
    - name: "8042"
      port: 8042
      targetPort: 8042
  selector:
    app: datanode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
  namespace: hadoop
spec:
  selector:
    matchLabels:
      app: datanode
  serviceName: datanode
  replicas: 4
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: datanode
    spec:
      terminationGracePeriodSeconds: 0
      setHostnameAsFQDN: true
      containers:
        - imagePullPolicy: Never
          image: hadoop-datanode
          name: datanode
          volumeMounts:
            - mountPath: /data/hdfs
              name: datanode-data
  volumeClaimTemplates:
    - metadata:
        name: datanode-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
