apiVersion: v1
kind: Service
metadata:
  labels:
    app: dfsadmin
  name: dfsadmin
  namespace: hadoop
spec:
  clusterIP: None
  selector:
    app: dfsadmin
---
apiVersion: v1
kind: Pod
metadata:
  name: dfsadmin
  namespace: hadoop
  labels:
    app: dfsadmin
spec:
  containers:
    - name: dfsadmin
      image: hadoop-dfsadmin:latest
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /work
          name: dfsadmin-work-dir
        - name: hadoop-conf
          mountPath: "/etc/hadoop/core-site.xml"
          subPath: core-site.xml
          readOnly: true
        - name: hadoop-conf
          mountPath: "/etc/hadoop/hdfs-site.xml"
          subPath: hdfs-site.xml
          readOnly: true
        - name: hadoop-conf
          mountPath: "/etc/hadoop/yarn-site.xml"
          subPath: yarn-site.xml
          readOnly: true
        - name: hadoop-conf
          mountPath: "/etc/hadoop/mapred-site.xml"
          subPath: mapred-site.xml
          readOnly: true
        - name: hadoop-conf
          mountPath: "/etc/hadoop/hadoop-env.sh"
          subPath: hadoop-env.sh
          readOnly: true
  volumes:
    - name: dfsadmin-work-dir
      hostPath:
        path: /work
        type: Directory
    - name: hadoop-conf
      configMap:
        name: hadoop-conf
  initContainers:
    - name: init-namenode
      image: busybox
      command: ['sh', '-c', "until nslookup namenode-0.namenode.hadoop.svc.localho.st; do echo Waiting for namenode to come online; sleep 2; done"]
  terminationGracePeriodSeconds: 0
  setHostnameAsFQDN: true
  dnsPolicy: ClusterFirst
