apiVersion: v1
kind: Service
metadata:
  labels:
    app: resourcemanager
  name: resourcemanager
  namespace: hadoop
spec:
  clusterIP: None
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
  selector:
    app: resourcemanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resourcemanager
  name: resourcemanager
  namespace: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resourcemanager
    spec:
      terminationGracePeriodSeconds: 0
      setHostnameAsFQDN: true
      initContainers:
        - name: init-namenode
          image: busybox
          command: ['sh', '-c', "until nslookup namenode; do echo Waiting for namenode to come online; sleep 2; done"]
      containers:
        - imagePullPolicy: Never
          image: hadoop-resourcemanager
          name: resourcemanager
      restartPolicy: Always
status: {}